local ENUMS = {}

ENUMS.GAME_STATE = {
	PAUSE = "PAUSE",
	TUTORIAL_WAIT = "TUTORIAL_WAIT",
	RUN = "RUN",
	MENU = "MENU",
}

ENUMS.ANIMATION = {
	IDLE = "IDLE",
	REVIVE = "REVIVE",
	RUN = "RUN",
	PAUSE = "PAUSE",
	DIE = "DIE",
	MENU = "MENU",
}

ENUMS.PLAYER_EFFECT = {
	COLLECT_GEM = "COLLECT_GEM",
	COLLECT_POWERUP = "COLLECT_POWERUP"
}

ENUMS.GEMS_ADD_TYPE = {
	UNKNOWN = "UNKNOWN",
	SHOP_OFFER = "SHOP_OFFER",
	TASK_REWARD = "TASK_REWARD",
	DAILY_REWARD = "DAILY_REWARD"
}

ENUMS.GEMS_SPEND_TYPE = {
	UNKNOWN = "UNKNOWN"
}

ENUMS.STAR_ADD_TYPE = {
	UNKNOWN = "UNKNOWN",
}

return ENUMS