local M = {}
M.WINDOW_RESIZED = "WINDOW_RESIZED"
M.STORAGE_CHANGED = "STORAGE_CHANGED"
M.STORAGE_SAVED = "STORAGE_SAVED"
M.SCENE_CHANGED = "SCENE_CHANGED"
M.GEMS_ADD = "GEMS_ADD"
M.GEMS_SPEND = "GEMS_SPEND"
M.STAR_ADD = "STAR_ADD"
M.NEW_HIGHSCORE = "NEW_HIGHSCORE"
M.MISSION_COMPLETED = "MISSION_COMPLETED"
M.DAILY_GEM_COLLECT = "DAILY_GEM_COLLECT"
M.JSTODEF = "JSTODEF"
M.WINDOW_EVENT = "WINDOW_EVENT"

return M